name: Generate GitHub Stats

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: stats
          options: 'username=${{ github.repository_owner }}&show_icons=true&theme=tokyonight&hide_border=true'
          path: profile/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate GitHub Streak
        run: |
          curl -L -f \
          -o profile/streak-dark.svg \
          "https://github-readme-streak-stats.herokuapp.com/?user=${{ github.repository_owner }}&theme=tokyonight&hide_border=true"

      - name: Commit generated cards
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/stats-dark.svg
          git add profile/streak-dark.svg

          git commit -m "Update GitHub stats cards" || exit 0
          git push
